### PR TITLE
ABE URL read from environment variable

### LINKED ISSUE #77: Set ABE URL with server environment variable
Requires moving from Node server to something like Flask, I think.

### PR DESCRIPTION
**Pull request by kylecombes**
Closes #77

### CODE REVIEW

**Comment by kylecombes** [comment]
@audreywl please don't merge yet. There's a problem.

**Comment by audreywl** [comment]
gotcha. can you also update the README with these changes?

**Comment by kylecombes** [comment]
OK, @audreywl, it's all working! Review away!

**Comment by audreywl** [comment]
looks good!

**Pull request merged**
